services:
  db:
    image: postgres
    container_name: pg-database
    environment:
      POSTGRES_DB: measures-bills
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
